### ISSUE TITLE
"No" shown as "false"

### ISSUE THREAD

**Issue by micred** [zmbacker/enum_help#24]
When I have an enum option that is translated as "No", simple_form shows "false".
Am I wrong?

PS: workaround is adding a space after "No":

    enums:
      user:
        product_already_have_km:
          already_customer: 'Sì'
          new_customerr: 'No '

**Comment by knu** [comment]
`'No'` should work.  A bare word `No` means false in YAML, which I guess it was the case for you.
```yaml
      new_customerr: No #=> false
      new_customerr: 'No' #=> "No"
      new_customerr: "No" #=> "No"
```
You should also be careful if you use "yes" as a key.
```yaml
      no: 'Sì' # Bad; the key is treated as `true`.
      'no': 'Sì' # Good
```
